import React, {useState} from 'react';
import Chat from './Chat';
import Login from './Login';
import Users from './Users';
import {
  get,
  getDatabase,
  onValue,
  push,
  ref,
  set,
  update,
} from 'firebase/database';

export default function ChatApp() {
  const [currentPage, setCurrentPage] = useState('login');
  const [username, setUsername] = useState(null);
  const [users, setUsers] = useState([]);
  const [userToAdd, setUserToAdd] = useState(null);
  const [selectedUser, setSelectedUser] = useState(null);
  const [myData, setMyData] = useState(null);

  const onLogin = async () => {
    const database = getDatabase();

    try {
      //first check if the user registered before
      const user = await findUser(username);

      if (user) {
        setMyData(user);
      } else {
        //create a new user
        const myDataObj = {
          username: username,
          avatar: 'https://i.pravatar.cc/150?u=' + Date.now(),
        };

        set(ref(database, 'users/' + username), myDataObj);
        setMyData(myDataObj);
      }

      // set friends list change listener
      const myUserRef = ref(database, 'users/' + username);
      onValue(myUserRef, snapshot => {
        const data = snapshot.val();
        setUsers(data.friends);
        setMyData(prev => ({
          ...prev,
          friends: data.friends,
        }));
      });

      setCurrentPage('users');
    } catch (error) {
      console.error(error);
    }
  };
  const onClickUser = user => {
    setCurrentPage('chat');
    setSelectedUser(user);
  };

  const onAddFriend = async name => {
    const database = getDatabase();

    try {
      const user = await findUser(name);

      if (user) {
        if (user.username === myData.username) {
          // don't let user add himself
          return;
        }

        if (
          myData.friends &&
          myData.friends.findIndex(f => f.username === user.username) > 0
        ) {
          // don't let user add a user twice
          return;
        }

        // Generate a reference to a new location and add some data using push()

        var newChatRoomRef = push(ref(database, 'chatrooms'), {
          firstUser: myData.username,
          secondUser: user.username,
          messages: [],
        });

        // Get the unique ID generated by push() by accessing its key
        const newChatRoomId = newChatRoomRef.key;

        const userFriends = user.friends ? user.friends : [];
        //join myself to this user friend list
        update(ref(database, 'users/' + user.username), {
          friends: [
            ...userFriends,
            {
              username: myData.username,
              avatar: myData.avatar,
              chatroomId: newChatRoomId,
            },
          ],
        });

        const myFriends = myData.friends ? myData.friends : [];
        //add this user to my friend list
        update(ref(database, 'users/' + myData.username), {
          friends: [
            ...myFriends,
            {
              username: user.username,
              avatar: user.avatar,
              chatroomId: newChatRoomId,
            },
          ],
        });
      }
    } catch (error) {
      console.error(error);
    }
  };

  const findUser = async name => {
    const database = getDatabase();

    const snapshot = await get(ref(database, `users/${name}`));

    return snapshot.val();
  };

  const onBack = () => {
    setCurrentPage('users');
  };

  switch (currentPage) {
    case 'login':
      return (
        <Login
          onLogin={onLogin}
          username={username}
          setUsername={setUsername}
        />
      );
    case 'users':
      return (
        <Users
          users={users}
          onClickUser={onClickUser}
          userToAdd={userToAdd}
          setUserToAdd={setUserToAdd}
          onAddFriend={onAddFriend}
        />
      );
    case 'chat':
      return (
        <Chat myData={myData} selectedUser={selectedUser} onBack={onBack} />
      );
    default:
      return null;
  }
}
